### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vprelovac** [sveltejs/hn.svelte.dev#10]
It is dissapointing that your flagship demo has zero documentation/instructions and it does not work.

I assumed the way to run this was yarn/yurn run dev/yarn start based on the previously deprecated project that had a Readme.

Even with that Error: Cannot find module 'svelte/store.mjs' is thrown.

**Comment by srinivasrk** [comment]
Yes, same issue here. It's got something do to with rollup I think. Commenting out the service worker out of rollup config removed that error. (not that this is the solution)

**Comment by webid** [comment]
Try updating sapper version in package.json ( v0.27.9 worked for me ) and editing '__sapper__/build/server/server.js'  L11 to `var store_mjs = require('svelte/store');`

**Comment by Rich-Harris** [comment]
Dependencies had got out of date somehow — fixed now
