### ISSUE TITLE
Build fails with error compiling CSS

### ISSUE THREAD

**Issue by benmccann** [sveltejs/hn.svelte.dev#16]
@pngwn helped me investigate yesterday

`npm run sapper` fails with errors like:
>> Building...
> Failed to build — error in src/routes/_layout.svelte: Expected }
1: main.svelte-1uhnsl8{position:relative;max-width:56em;background-color:white;padding:2em;margin:0 auto;box-sizing:border-box}

Things we found out:
* It builds on his two Mac machines including in Docker images he setup, but does not build on my two Ubuntu machines, codeanywhere, or GitHub actions
  * GitHub actions was setup to run on Node 10, 12, 14 on Windows, Linux, and Mac. It failed on all 9 combinations
* It builds if you remove all CSS, but fails if you have any CSS
* [The RealWorld example](https://github.com/sveltejs/realworld) builds, but it's not clear what's different between the two examples
* It's been failing since the initial commit

**Comment by Rich-Harris** [comment]
i think we can close this now that deps are updated

**Comment by benmccann** [comment]
@Rich-Harris no, I'm afraid this one is still an issue. Look at the CI. It's still failing

**Comment by pngwn** [comment]
Just to clarify, it isn’t only failing in CI. There are people who are unable to run this locally with the same errors as are occurring in CI. 

I’m guessing Rich is having the same experience as I am, which is that everything is working fine.

**Comment by benmccann** [comment]
What do you get if you run `npm config list`? I'm wondering if you setup some `npm` config that I might be missing
