### ISSUE TITLE
fix CI errors

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/hn.svelte.dev#20]
`npm run sapper` works locally but not in CI... and it's something to do with this:

```
> Building...
> Failed to build — error in /Users/runner/runners/2.262.1/work/hn.css.dev/hn.svelte.dev/src/routes/_layout.svelte: Expected }
1: main.svelte-12dt5ya{position:relative;max-width:56em;padding:2em;margin:0 auto;box-sizing:border-box}
```

It's putting the project in `hn.svelte.dev` and somehow that is getting rewritten to `hn.css.dev` and somehow that is breaking stuff. beyond that i am at a loss

**Comment by benmccann** [comment]
Wow. Good eye! @pngwn and I spent hours trying to figure this out.

I guess he must have checked out the project from GitHub with a different name, which is why it worked for him and not me

**Comment by pngwn** [comment]
Ah yes I did. I always change the names. 

Also I hate technology.

**Comment by Rich-Harris** [comment]
The sight of the svelte -> css string replacement awakened a long dormant memory that I once renamed the repo locally from `hn.svelte.dev` to `hn-svelte-dev` because I was too busy to fix it...
