### ISSUE TITLE
/new results in 500

### ISSUE THREAD

**Issue by joshuarli** [sveltejs/hn.svelte.dev#4]
https://api.hnpwa.com/v0/newest/1.json gives `Error: could not handle the request`, resulting in 500.

Related: https://github.com/davideast/hnpwa-api/issues/11

Probably just use the working https://api.hnpwa.com/v0/newest.json?page=1 endpoint.

**Comment by default-writer** [comment]
https://api.hnpwa.com/v0/newest/1.json is working close isssue @joshuarli
