### ISSUE TITLE
Disallow Search Engines From Indexing hn.svelte.technology

### ISSUE THREAD

**Issue by nikhiljha** [sveltejs/hn.svelte.dev#7]
I'm still new to Svelte, so every time I want to search up something related to Svelte, almost the entire first page is from hn.svelte.technology.

<img width="942" alt="Screen Shot 2019-07-13 at 6 02 04 PM" src="https://user-images.githubusercontent.com/2773700/61178029-5a4b3100-a598-11e9-923f-0a0f729163b3.png">

None of these results really have anything to do with Svelte. I know I can do `-site:hn.svelte.technology` to exclude results from there (and it works well), but it's still *really* annoying to have to type it out every time. Besides, it's probably not the best idea to be rehosting someone else's content and having it be indexed by search engines.

This can be fixed by changing the robots.txt of that site to disallow everything.

**Comment by Conduitry** [comment]
Transferred this issue from https://github.com/sveltejs/svelte/issues/3240 to https://github.com/sveltejs/hn.svelte.dev/issues/7

Adding a robots.txt makes sense. A `User-agent: * Disallow: /` would presumably suffice, but I don't know whether that would be overkill or prevent some things we would like to keep.

**Comment by nikhiljha** [comment]
```robots.txt
User-agent: *
Disallow: /item
```

Would work too, that way this site still shows up on Google, but not the individual comment pages.

**Comment by RStrydom** [comment]
Hey @nikhiljha I added a pull request #9 . I made it `/` as the root redirects you to `/top/1` anyways. Let me know if you foresee any issues?

**Comment by RStrydom** [comment]
Hi @Conduitry can we possible merge this? #9 :smile_cat:
